name: Owoifier
description: owoifier owoifies your server!
main: xyz.nkomarn.owoifier.Owoifier
version: '1.3'
author: TechToolbox (@nkomarn)
website: https://nkomarn.xyz
api-version: '1.13'
permissions:
  owoifier.use:
    description: Enables owoifier for people with this permission
    default: false
    children:
      owoifier.use.chat: true
      owoifier.use.sign: true
  owoifier.use.chat:
    description: Enables owoifier on only chat for people with this permission
    default: false
  owoifier.use.sign:
    description: Enables owoifier on only signs for people with this permission
    default: false